# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="aphex"


# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git
vi-mode
zsh-autosuggestions
H-S-MW
pip
shrink-path
zsh-syntax-highlighting
autojump
)

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

source $ZSH/oh-my-zsh.sh

# User configuration

HISTSIZE=999999999
SAVEHIST=$HISTSIZE
HISTFILE=~/.zsh_history

#setopt share_history
#setopt histignorealldups
#setopt incappendhistory

#aliases
alias rsp='rsync -vP'
alias waf="$PWD/modules/waf/waf-light"
alias ccat='pygmentize -g -O style=colorful,linenos=1'
alias realpath='python3 -c "import os; import sys; print(os.path.realpath(sys.argv[1]))"'
alias pip='pip3'
alias python='python3'
alias xargs='xargs ' # aliased commands passed to xargs will be expanded

case `uname` in
      Darwin)
        alias nproc='sysctl -n hw.physicalcpu'
;;
esac

export GCC_COLORS=auto
stty -ixon
ACK_PAGER=less

export HOMEBREW_GITHUB_API_TOKEN=8909cfa3fe297c1860a23f760d61e6ec2b5d3853

export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
if [ -d "$HOME/Library/Android/sdk/platform-tools" ] ; then
 export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"
fi

export PATH="/usr/local/opt/llvm/bin:$PATH"
export PATH="/Users/and_marsh/.cargo/bin:$PATH"

# export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
# export JAVA_11_HOME=$(/usr/libexec/java_home -v11)

# alias java8='export JAVA_HOME=$JAVA_8_HOME'
# alias java11='export JAVA_HOME=$JAVA_11_HOME'

# default to Java 11
# java11
export JAVA_HOME="/opt/homebrew/opt/openjdk@17"
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

export ANDROID_SDK_ROOT="/Users/and_marsh/Library/Android/sdk"
export ANDROID_HOME="/Users/and_marsh/Library/Android/sdk"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
export PATH="/Users/and_marsh/Projects/cart_craft/flutter/bin:$PATH"

export PATH="/Applications/CMake.app/Contents/bin:$PATH"

export FLYCTL_INSTALL="$HOME/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"
